// Data latih buat model Naive Bayes (kategorisasi otomatis transaksi)
const TRAINING_DATA = [
{"t":"makan siang di warteg","c":"Makanan"},
{"t":"beli nasi padang","c":"Makanan"},
{"t":"jajan indomie","c":"Makanan"},
{"t":"makan malam di resto","c":"Makanan"},
{"t":"beli kopi kekinian","c":"Makanan"},
{"t":"sarapan bubur ayam","c":"Makanan"},
{"t":"beli snack di minimarket","c":"Makanan"},
{"t":"makan bakso","c":"Makanan"},
{"t":"beli ayam geprek","c":"Makanan"},
{"t":"jajan cimol","c":"Makanan"},
{"t":"beli galon air minum","c":"Makanan"},
{"t":"delivery makanan online","c":"Makanan"},
{"t":"beli buah di pasar","c":"Makanan"},
{"t":"makan di kantin kampus","c":"Makanan"},
{"t":"beli gorengan","c":"Makanan"},
{"t":"naik ojek online ke kampus","c":"Transportasi"},
{"t":"isi bensin motor","c":"Transportasi"},
{"t":"naik angkot","c":"Transportasi"},
{"t":"bayar parkir motor","c":"Transportasi"},
{"t":"naik bus antar kota","c":"Transportasi"},
{"t":"beli tiket kereta","c":"Transportasi"},
{"t":"servis motor","c":"Transportasi"},
{"t":"ganti oli motor","c":"Transportasi"},
{"t":"naik grab ke rumah","c":"Transportasi"},
{"t":"bayar tol","c":"Transportasi"},
{"t":"beli helm baru","c":"Transportasi"},
{"t":"top up e-toll","c":"Transportasi"},
{"t":"naik pesawat pulang kampung","c":"Transportasi"},
{"t":"bayar spp semester","c":"Pendidikan"},
{"t":"beli buku kuliah","c":"Pendidikan"},
{"t":"fotocopy modul","c":"Pendidikan"},
{"t":"print tugas skripsi","c":"Pendidikan"},
{"t":"bayar ukt","c":"Pendidikan"},
{"t":"beli alat tulis","c":"Pendidikan"},
{"t":"ikut kursus online","c":"Pendidikan"},
{"t":"beli laptop buat kuliah","c":"Pendidikan"},
{"t":"bayar wisuda","c":"Pendidikan"},
{"t":"beli kertas hvs","c":"Pendidikan"},
{"t":"daftar seminar proposal","c":"Pendidikan"},
{"t":"beli jurnal referensi","c":"Pendidikan"},
{"t":"nonton bioskop","c":"Hiburan"},
{"t":"langganan netflix","c":"Hiburan"},
{"t":"main game online beli item","c":"Hiburan"},
{"t":"nongkrong di cafe","c":"Hiburan"},
{"t":"karaoke bareng teman","c":"Hiburan"},
{"t":"beli tiket konser","c":"Hiburan"},
{"t":"langganan spotify","c":"Hiburan"},
{"t":"jalan-jalan ke mall","c":"Hiburan"},
{"t":"main futsal","c":"Hiburan"},
{"t":"beli pulsa buat streaming","c":"Hiburan"},
{"t":"liburan ke pantai","c":"Hiburan"},
{"t":"beli baju baru","c":"Belanja"},
{"t":"beli sepatu","c":"Belanja"},
{"t":"belanja bulanan di supermarket","c":"Belanja"},
{"t":"beli skincare","c":"Belanja"},
{"t":"beli tas","c":"Belanja"},
{"t":"belanja online di marketplace","c":"Belanja"},
{"t":"beli aksesoris hp","c":"Belanja"},
{"t":"beli perlengkapan mandi","c":"Belanja"},
{"t":"beli casing hp","c":"Belanja"},
{"t":"belanja kebutuhan kos","c":"Belanja"},
{"t":"beli obat di apotek","c":"Kesehatan"},
{"t":"periksa ke dokter","c":"Kesehatan"},
{"t":"beli vitamin","c":"Kesehatan"},
{"t":"bayar bpjs","c":"Kesehatan"},
{"t":"beli masker medis","c":"Kesehatan"},
{"t":"konsultasi psikolog","c":"Kesehatan"},
{"t":"cek kesehatan di puskesmas","c":"Kesehatan"},
{"t":"beli suplemen","c":"Kesehatan"},
{"t":"periksa gigi","c":"Kesehatan"},
{"t":"beli hand sanitizer","c":"Kesehatan"},
{"t":"gaji bulanan","c":"Pemasukan"},
{"t":"uang saku dari orang tua","c":"Pemasukan"},
{"t":"dapat bonus kerja","c":"Pemasukan"},
{"t":"hasil jual barang bekas","c":"Pemasukan"},
{"t":"dapat uang dari freelance","c":"Pemasukan"},
{"t":"terima transferan","c":"Pemasukan"},
{"t":"dapat beasiswa","c":"Pemasukan"},
{"t":"hasil jualan online","c":"Pemasukan"},
{"t":"dapat thr","c":"Pemasukan"},
{"t":"uang hasil part time","c":"Pemasukan"},
{"t":"bayar listrik kos","c":"Lainnya"},
{"t":"bayar wifi","c":"Lainnya"},
{"t":"bayar kos bulanan","c":"Lainnya"},
{"t":"donasi ke panti asuhan","c":"Lainnya"},
{"t":"bayar iuran organisasi","c":"Lainnya"},
{"t":"transfer ke teman","c":"Lainnya"},
{"t":"bayar denda","c":"Lainnya"},
{"t":"beli pulsa","c":"Lainnya"},
{"t":"bayar cicilan","c":"Lainnya"},
{"t":"sumbangan kegiatan kampus","c":"Lainnya"}
];
